  function [IE_VND, IA_VND]= EXIT_LDPC_AWGN_VND(IA_ch)
IA_VND=0:0.001:1;
IA_VND(end) = 0.999999;
% IA_ch = 0.77;
% for jj=1:23 
for ii=1:length(IA_VND)
%   IE_VND(ii) =  12960/64800*(j_function(sqrt((8-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 19440/64800*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 32399/64800*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 1/64800*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));
% IE_VND(ii) =  36/180*(j_function(sqrt((8-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 54/180*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 89/180*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 1/180*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));
% rate 1/2 skale terkecil
% IE_VND(ii) =  36/540*(j_function(sqrt((13-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 324/540*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 179/540*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 1/540*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));
%             rate 2/3 skala 1/120
% IE_VND(ii) =  108/540*(j_function(sqrt((8-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 162/540*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 269/540*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 1/540*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));
%             rate 1/2 skala 1/120
% IE_VND(ii) =  2520/3240*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...    
%                 719/3240*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 1/3240*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));
%             skala 1/60
%             IE_VND(ii) =  198/270*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...    
%                 71/270*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 1/270*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));


%ORI
IE_VND(ii) =  12600/16200*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...    
                3599/16200*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
                1/16200*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));




%             PEG 4/5
            IE_VND(ii) =  210/270*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...    
                59/270*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
                1/270*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));

% skala 1/120 64800
%             IE_VND(ii) = 54/540*(j_function(sqrt((11-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 378/540*(j_function(sqrt((3-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...    
%                 107/540*(j_function(sqrt((2-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)))+...
%                 1/540*(j_function(sqrt((1-1)*(inverseJfunction(IA_VND(ii)))^2+inverseJfunction(IA_ch)^2)));

end
% figure

 plot(IA_VND,IE_VND,'r:','linewidth',1)
 xlabel('I_{A,VND},I_{E,CND}');
ylabel('I_{E,VND},I_{A,CND}');
   end